<h3>Karlsruhe Python Meetup</h3>
<h1>Know Your NumPy</h1>
<p>
<small>by Dirk Toewe</small>
</p>

# What's NumPy

<ul>
  <li>Numerics Library
  <li>Revolves around nd-Array type
  <li>Building block for many packages
  <ul>
    <li>Natural&nbsp;Sciences, Machine&nbsp;Learning,<br>Visualization, ...
  </ul>
  <li>Accompanied by <a href="https://docs.scipy.org/doc/scipy/reference/">SciPy</a>
  <ul>
    <li>(Sparse)&nbsp;Linear&nbsp;Algebra, Optimization, Signal&nbsp;Processing, ...
  </ul>
</ul>

# 1D-Arrays

Are similar to <code>lists</code> (NumPy often accepts <code>list</code> inputs).

In [1]:
import numpy as np

array1d = np.array([1,2,3,4])

In [2]:
array1d.ndim

1

In [3]:
array1d.shape

(4,)

In [4]:
array1d.dtype

dtype('int64')

# 2D-Arrays

Are similar to nested <code>lists</code> (NumPy accepts those, too).

In [5]:
array2d = np.array(
  [[1.1, 1.2, 1.3],
   [2.1, 2.2, 2.3]]
)

In [6]:
array2d.ndim

2

In [7]:
array2d.shape

(2, 3)

In [8]:
array2d.dtype

dtype('float64')

# 3D-Arrays

More nesting...

In [9]:
array3d = np.array(
  [[[111, 112, 113, 114],
    [121, 122, 123, 124],
    [131, 132, 133, 134]],
   [[211, 212, 213, 214],
    [221, 222, 223, 224],
    [231, 232, 233, 234]]]
)

In [10]:
array3d.ndim

3

In [11]:
array3d.shape

(2, 3, 4)

# 0D-Arrays

In [12]:
array0d = np.array(True)

In [13]:
array0d.ndim

0

In [14]:
array0d.shape

()

In [15]:
array0d.dtype

dtype('bool')

# Data Types
<br>
<dl>
  <dt>bool<dd>bool
  <dt>int<dd>uint8, ..., int64
  <dt>float<dd>float16, float32, float64, float128
  <dt>complex<dd>complex64, complex128
  <dt>str<dd>Strings
  <dt>object<dd>Any Python object
</dl>

# Factory Methods

In [16]:
np.zeros([2,1000], dtype=np.int32)

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int32)

In [17]:
np.arange( start=0, stop=10*1000, step=2 )

array([   0,    2,    4, ..., 9994, 9996, 9998])

In [18]:
np.linspace( start=0, stop=1, num=3 )

array([0. , 0.5, 1. ])

In [19]:
np.random.rand(2,4)

array([[0.67011479, 0.55388689, 0.01934717, 0.54479296],
       [0.41982803, 0.74279145, 0.04674466, 0.07281442]])

# Indexing

In [20]:
array2d = np.array(
  [[11, 12, 13, 14],
   [21, 22, 23, 24],
   [31, 32, 33, 34]]
)

In [21]:
array2d[1][2]

23

In [22]:
array2d[1,2]

23

In [23]:
array2d[2]

array([31, 32, 33, 34])

In [24]:
array2d[:,2]

array([13, 23, 33])

# More Indexing

In [25]:
array3d = np.array(
  [[[111,112,113,114],
    [121,122,123,124]],
   [[211,212,213,214],
    [221,222,223,224]]]
)

In [26]:
array3d[...,2]

array([[113, 123],
       [213, 223]])

In [27]:
array3d[0,0,-1]

114

In [28]:
array3d[0,0,[1,2,3]]

array([112, 113, 114])

# Masking

In [29]:
a = np.array(
  [[1,2,3],
   [4,5,6]]
)
b = np.array(
  [[10,20,30],
   [40,50,60]]
)
mask = np.array(
  [[True, False,True ],
   [False,True, False]]
)

In [30]:
np.where(mask, a,b)

array([[ 1, 20,  3],
       [40,  5, 60]])

In [31]:
a[mask] = 42
a

array([[42,  2, 42],
       [ 4, 42,  6]])

# Slicing

In [32]:
array2d = np.array(
  [[11, 12, 13, 14],
   [21, 22, 23, 24]]
)

In [33]:
start,end,step = 1,4,2
array2d[:, start:end:step]

array([[12, 14],
       [22, 24]])

In [34]:
array2d[:, -2:0:-1]

array([[13, 12],
       [23, 22]])

# Reshape

Maintains order in which nested list would be read by humans:<br>
(left to right, top to bottom).

In [35]:
array1d = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [36]:
array3d = array1d.reshape(2,2,2)
array3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [37]:
array3d.reshape(-1,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# Transpose

In [38]:
array3d = np.array(
  [[[111, 112, 113, 114],
    [121, 122, 123, 124],
    [131, 132, 133, 134]],
   [[211, 212, 213, 214],
    [221, 222, 223, 224],
    [231, 232, 233, 234]]]
)

In [39]:
array3d.transpose(2,1,0) # i,j,k -> k,j,i

array([[[111, 211],
        [121, 221],
        [131, 231]],

       [[112, 212],
        [122, 222],
        [132, 232]],

       [[113, 213],
        [123, 223],
        [133, 233]],

       [[114, 214],
        [124, 224],
        [134, 234]]])

# Unary Functions

In [40]:
np.sqrt(9)

3.0

In [41]:
x = np.sqrt([1,4,9,16])

In [42]:
x

array([1., 2., 3., 4.])

In [43]:
np.sqrt(
  [[ 1, 4, 9],
   [16,25,36]]
)

array([[1., 2., 3.],
       [4., 5., 6.]])

# Vectorize

In [44]:
def f( x ):
  return True if x == 42 else False

In [45]:
f( np.array([1,2,3,4]) )

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [46]:
g = np.vectorize(f)
g([1,2,42,4])

array([False, False,  True, False])

# Binary Operators

In [47]:
a = np.array(
  [[1 ,2],
   [3, 4]]
)
b = np.array(
  [[10,20],
   [30,40]]
)
a + b

array([[11, 22],
       [33, 44]])

In [48]:
c = a * b

In [49]:
c

array([[ 10,  40],
       [ 90, 160]])

# More Binary Operators

In [50]:
a = np.array([1,3,3,7])
b = np.array([7,3,3,1])

In [51]:
a < b

array([ True, False, False, False])

In [52]:
a == b

array([False,  True,  True, False])

In [53]:
(a < b) | (a == b)

array([ True,  True,  True, False])

In [54]:
a / b

array([0.14285714, 1.        , 1.        , 7.        ])

# Broadcasting Introduction

In [55]:
a = np.array(2)
b = np.array([1,2,3,4])
x = a*b

In [56]:
x

array([2, 4, 6, 8])

In [57]:
b = np.array( [ 1, 2, 3, 4])
c = np.array([[10,20,30,40],
              [50,60,70,80]])
y = b+c

In [58]:
y

array([[11, 22, 33, 44],
       [51, 62, 73, 84]])

<h1>Broadcasting Rules</h1>

<style>
  .reveal .slides section .fragment.step-fade-in-then-out {
	opacity: 0;
	display: none; }
  .reveal .slides section .fragment.step-fade-in-then-out.current-fragment {
	opacity: 1;
	display: inline; }
</style>

<p>
<div style="height: 80vh">




<div class="fragment step-fade-in-then-out">

<pre><code data-trim data-noescape>

<h3>Data</h3>
[[1],        
 [3],    <b>+</b>   [10,20]
 [5]]
<h3>Shapes</h3>
 (3,1)          (2,)

</code></pre>

</div>




<div class="fragment step-fade-in-then-out">

<pre><code data-trim data-noescape>

<h3>Data</h3>
[[1],        
 [3],    <b>+</b>  <span style="color:red">[</span>[10,20]<span style="color:red">]</span>
 [5]]
<h3>Shapes</h3>
 (3,1)         (<span style="color:red">1,</span>2)

</code></pre>

<ol>
  <li>Pad smaller of the shapes with 1s to the left.
</ol>

</div>




<div class="fragment step-fade-in-then-out">

<pre><code data-trim data-noescape>

<h3>Data</h3>
[[1],        
 [3],    <b>+</b>  [[10,20]]
 [5]]
<h3>Shapes</h3>
 (3,<span style="color:red">1</span>)         (1,2)
    <span style="color:red">^</span>             <span style="color:red">^</span>
</code></pre>

<ol>
  <li>Pad smaller of the shapes with 1s to the left
  <li><b>IF</b> <code>a.shape[i] == 1</code> <b>THEN</b> repeat <code>a</code> by <code>b.shape[i]</code> times along axis <code>i</code>
</ol>

</div>




<div class="fragment step-fade-in-then-out">

<pre><code data-trim data-noescape>

<h3>Data</h3>
[[1,1],        
 [3,3],  <b>+</b>  [[10,20]]
 [5,5]]
<h3>Shapes</h3>
 (3,2)         (1,2)
    <span style="color:red">^</span>             <span style="color:red">^</span>
</code></pre>

<ol>
  <li>Pad smaller of the shapes with 1s to the left
  <li><b>IF</b> <code>a.shape[i] == 1</code> <b>THEN</b> repeat <code>a</code> by <code>b.shape[i]</code> times along axis <code>i</code>
</ol>

</div>




<div class="fragment step-fade-in-then-out">

<pre><code data-trim data-noescape>

<h3>Data</h3>
[[1,1],        
 [3,3],  <b>+</b>  [[10,20]]
 [5,5]]
<h3>Shapes</h3>
 (3,2)         (1,2)
  <span style="color:red">^</span>             <span style="color:red">^</span>
</code></pre>

<ol>
  <li>Pad smaller of the shapes with 1s to the left
  <li><b>IF</b> <code>a.shape[i] == 1</code> <b>THEN</b> repeat <code>a</code> by <code>b.shape[i]</code> times along axis <code>i</code>
</ol>

</div>




<div class="fragment step-fade-in-then-out">

<pre><code data-trim data-noescape>

<h3>Data</h3>
[[1,1],        
 [3,3],  <b>+</b>  [[10,20]]
 [5,5]]
<h3>Shapes</h3>
 (3,2)         (<span style="color:red">1</span>,2)
  <span style="color:red">^</span>             <span style="color:red">^</span>
</code></pre>

<ol>
  <li>Pad smaller of the shapes with 1s to the left
  <li><b>IF</b> <code>a.shape[i] == 1</code> <b>THEN</b> repeat <code>a</code> by <code>b.shape[i]</code> times along axis <code>i</code>
  <li><b>IF</b> <code>b.shape[i] == 1</code> <b>THEN</b> repeat <code>b</code> by <code>a.shape[i]</code> times along axis <code>i</code>
</ol>

</div>




<div class="fragment step-fade-in-then-out">

<pre><code data-trim data-noescape>

<h3>Data</h3>
[[1,1],     [[10,20],
 [3,3],  <b>+</b>   [10,20],
 [5,5]]      [10,20]]
<h3>Shapes</h3>
 (3,2)         (3,2)
  <span style="color:red">^</span>             <span style="color:red">^</span>
</code></pre>

<ol>
  <li>Pad smaller of the shapes with 1s to the left
  <li><b>IF</b> <code>a.shape[i] == 1</code> <b>THEN</b> repeat <code>a</code> by <code>b.shape[i]</code> times along axis <code>i</code>
  <li><b>IF</b> <code>b.shape[i] == 1</code> <b>THEN</b> repeat <code>b</code> by <code>a.shape[i]</code> times along axis <code>i</code>
</ol>

</div>




<div class="fragment step-fade-in-then-out">

<pre><code data-trim data-noescape>

<h3>Data</h3>
[[1,1],     [[10,20],
 [3,3],  <b>+</b>   [10,20],
 [5,5]]      [10,20]]
<h3>Shapes</h3>
 (3,2)         (3,2)

</code></pre>

<ol>
  <li>Pad smaller of the shapes with 1s to the left
  <li><b>IF</b> <code>a.shape[i] == 1</code> <b>THEN</b> repeat <code>a</code> by <code>b.shape[i]</code> times along axis <code>i</code>
  <li><b>IF</b> <code>b.shape[i] == 1</code> <b>THEN</b> repeat <code>b</code> by <code>a.shape[i]</code> times along axis <code>i</code>
  <li><b>IF</b> shapes do not match <b>THEN</b> <code>a</code> and <code>b</code> are not broadcast-compatible.
</ol>

</div>

# Broadcasting Examples

In [59]:
i = np.arange(1024).reshape(-1,1)
j = np.arange(1024)

In [60]:
np.where( i==j, 1, 0 )

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 1]])

# Vectorize Supports Broadcasting

In [61]:
def f(x,y):
  return x if x >= y else y

g = np.vectorize(f)

In [62]:
a = np.array(
  [[1],
   [2],
   [3]]
)
b = np.array([1,2,3])

g(a,b)

array([[1, 2, 3],
       [2, 2, 3],
       [3, 3, 3]])

# Reduction

In [63]:
xy = np.random.rand(1024,2)
xy

array([[0.96952259, 0.3816399 ],
       [0.75507864, 0.73669978],
       [0.07124163, 0.60931331],
       ...,
       [0.95367635, 0.22638893],
       [0.54922544, 0.85568797],
       [0.17564332, 0.73608777]])

In [64]:
np.sum(xy, axis=0) / xy.shape[0]

array([0.5018996 , 0.50477921])

In [65]:
np.sum(xy, axis=(0,1))

1030.8390968521253

# More Reduction

In [66]:
with np.errstate(divide='ignore'):
  data = 1.0 / np.random.randint(-1,2, size=[8,2])
data

array([[-1.,  1.],
       [ 1., inf],
       [-1., inf],
       [inf,  1.],
       [-1., inf],
       [ 1.,  1.],
       [ 1.,  1.],
       [inf, inf]])

In [67]:
np.any(np.isinf(data), axis=1)

array([False,  True,  True,  True,  True, False, False,  True])

In [68]:
np.all(np.isfinite(data), axis=1)

array([ True, False, False, False, False,  True,  True, False])

# To Sum Up

  * You've been introduced to many parts of NumPy
  * The true power comes from combining these operations
  * Experimenting with NumPy helps a lot with understanding

<h3>Karlsruhe Python Meetup</h3>
<h1>Thank You for listening - Questions?</h1>
<p>
    <a href="https://github.com/DirkToewe/python_meetup_presentations">GitHub.com/DirkToewe/python_meetup_presentations</a>
</p>